version: "3"

services:
  graphdb:
    container_name: graphdb-preload
    # image: ontotext/graphdb:${GRAPHDB_VERSION}-ee
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        version: ${GRAPHDB_VERSION}

    # Load all files from ../import in repo defined in ./graphdb-repo-config.ttl
    entrypoint: [ "/opt/graphdb/dist/bin/preload", "--force", "--recursive", "-q", "/tmp", "-c", "/opt/graphdb/graphdb-repo-config.ttl", "/opt/graphdb/home/graphdb-import" ]

    # Preload given file to existing repository (here "demo")
    # entrypoint: [ "/opt/graphdb/dist/bin/preload", "-f", "-i", "demo", "/root/graphdb-import" ]

    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx${GRAPHDB_HEAP_SIZE} -Xms${GRAPHDB_HEAP_SIZE}
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    volumes:
      # Change folders in the .env file or directly here
      - ${GRAPHDB_HOME}:/opt/graphdb/home
      - ${IMPORT_FOLDER}:/opt/graphdb/home/graphdb-import
      - ${REPOSITORY_CONFIG_FILE}:/opt/graphdb/graphdb-repo-config.ttl
